apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgmt-startseite-deployment
  namespace: startseite
  labels:
    app: mgmt-startseite
    build_number:  B${BUILD_NUMBER}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mgmt-startseite      
  template:
    metadata:
      labels:
        app: mgmt-startseite
        build_number:  B${BUILD_NUMBER}
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: "0.0.0.0/0"
    spec:
      containers:
      - name: mgmt-startseite
        image: container.velocloud.ta-systeme.com/de/mgmt-startseite:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits: 
              cpu: "300m"
              memory: "300Mi"
